package uk.gov.moj.cpp.sjp.command.controller.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;

rule "Command - Rule for update financial means"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.command.update-financial-means" || name == "sjp.command.update-all-financial-means");
  then
    $outcome.setSuccess(true);
end
