package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;

rule "Command Controller - Update plea"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.command.update-plea");
  then
    $outcome.setSuccess(true);
end

rule "Command Controller - Cancel plea"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.command.cancel-plea");
  then
    $outcome.setSuccess(true);
end