package uk.gov.moj.cpp.sjp.command.controller.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import java.util.Arrays;
import uk.gov.moj.cpp.sjp.command.controller.accesscontrol.RuleConstants;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for Upload Case Document"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.command.upload-case-document");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getUploadCaseDocumentActionGroups()))
  then
    $outcome.setSuccess(true);
end
