package uk.gov.moj.cpp.sjp.command.controller.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;

rule "Command - Rule for update employer"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.command.update-employer");
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for delete employer"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.command.delete-employer");
  then
    $outcome.setSuccess(true);
end

