package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;

rule "Command - reserve case"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.command.reserve-case");
  then
    $outcome.setSuccess(true);
end

rule "Command - undo reserve case"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.command.undo-reserve-case");
  then
    $outcome.setSuccess(true);
end