package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.sjp.command.controller.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for Update defendant national insurance number"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.update-defendant-national-insurance-number");
  then
    $outcome.setSuccess(true);
end
