package uk.gov.moj.cpp.sjp.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.sjp.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command API - update offence code"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.update-offence-code");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getCreateSjpCaseActionGroups()));
  then
    $outcome.setSuccess(true);
end
