    package uk.gov.moj.cpp.accesscontrol;

    import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
    import uk.gov.moj.cpp.accesscontrol.drools.Action;
    import uk.gov.moj.cpp.sjp.command.api.accesscontrol.RuleConstants;

    global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

    rule "Command - Rule for Remove Person Info"
      when
        $outcome: Outcome();
        $action: Action(name == "sjp.remove-person-info");
        eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getRemovePersonInfoGroups()));
      then
        $outcome.setSuccess(true);
    end
