package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.sjp.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - API - Action - sjp.add-request-for-outstanding-fines"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.add-request-for-outstanding-fines");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getAddRequestForOutstandingFinesGroups()));
  then
    $outcome.setSuccess(true);
end