package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.sjp.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for Associate Enterprise ID"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.associate-enterprise-id");
        eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end



