package uk.gov.moj.cpp.sjp.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.sjp.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for reject pending defendant changes"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.reject-pending-defendant-changes");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getRejectPendingDefendantChanges()));
  then
    $outcome.setSuccess(true);
end
