package uk.gov.moj.cpp.sjp.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.sjp.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for acknowledge defendant details updates"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.acknowledge-defendant-details-updates");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getAcknowledgeDefendantDetailsUpdatesGroups()));
  then
    $outcome.setSuccess(true);
end
