package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import java.util.Arrays;
import uk.gov.moj.cpp.sjp.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for starting session"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.start-session");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getStartSessionGroups()));
  then
    $outcome.setSuccess(true);
end
