package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import java.util.Arrays;
import uk.gov.moj.cpp.sjp.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for Cancel Withdrawl all offences"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.cancel-request-withdrawal-all-offences");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getCancelRequestWithdrawalOfAllOffencesGroups()));
  then
    $outcome.setSuccess(true);
end

