package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.sjp.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for mark case reopened in libra"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.mark-case-reopened-in-libra");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getCaseReopenedActionGroups()));
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for update case reopened in libra"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.update-case-reopened-in-libra");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getCaseReopenedActionGroups()));
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for undo case reopened in libra"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.undo-case-reopened-in-libra");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getCaseReopenedActionGroups()));
  then
    $outcome.setSuccess(true);
end