package uk.gov.moj.cpp.sjp.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.sjp.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for Mark Case Legal SOC Checked"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.mark-as-legal-soc-checked");
        eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getMarkAsLegalSocCheckedGroups()));
  then
    $outcome.setSuccess(true);
end



