package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.sjp.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command API - Rule for Add Dates To Avoid"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.add-dates-to-avoid");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getAddDatesToAvoidActionGroups()));

  then
    $outcome.setSuccess(true);
end