package uk.gov.moj.cpp.sjp.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import java.util.Arrays;
import uk.gov.moj.cpp.sjp.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for case complete bdf"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.case-complete-bdf");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getCaseCompleteBdfGroups()));
  then
    $outcome.setSuccess(true);
end

