package uk.gov.moj.cpp.sjp.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import java.util.Arrays;
import uk.gov.moj.cpp.sjp.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for Create Case Application"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.create-case-application");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getCreateCaseApplicationGroups()));
  then
    $outcome.setSuccess(true);
end