#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/listener/message/sjp

version: v1
/sjp.event:
  post:
    body:
      application/vnd.sjp.events.case-document-added+json:
        schema: !include json/schema/sjp.events.case-document-added.json
        example: !include json/sjp.events.case-document-added.json

      application/vnd.sjp.events.case-received+json:
        example: !include json/sjp.events.case-received.json
        schema: !include json/schema/sjp.events.case-received.json

      application/vnd.sjp.events.sjp-case-created+json:
        example: !include json/sjp.events.sjp-case-created.json
        schema: !include json/schema/sjp.events.sjp-case-created.json

      application/vnd.sjp.events.plea-updated+json:
        schema: !include json/schema/sjp.events.plea-updated.json
        example: !include json/sjp.events.plea-updated.json

      application/vnd.sjp.events.plea-cancelled+json:
        schema: !include json/schema/sjp.events.plea-cancelled.json
        example: !include json/sjp.events.plea-cancelled.json

      application/vnd.sjp.events.case-completed+json:
        schema: !include json/schema/sjp.events.case-completed.json
        example: !include json/sjp.events.case-completed.json

      application/vnd.sjp.events.court-referral-created+json:
        schema: !include json/schema/sjp.events.court-referral-created.json
        example: !include json/sjp.events.court-referral-created.json

      application/vnd.sjp.events.court-referral-actioned+json:
        schema: !include json/schema/sjp.events.court-referral-actioned.json
        example: !include json/sjp.events.court-referral-actioned.json

      application/vnd.sjp.events.financial-means-updated+json:
        schema: !include json/schema/sjp.events.financial-means-updated.json
        example: !include json/sjp.events.financial-means-updated.json

      application/vnd.sjp.events.employer-updated+json:
        schema: !include json/schema/sjp.events.employer-updated.json
        example: !include json/sjp.events.employer-updated.json

      application/vnd.sjp.events.employer-deleted+json:
        schema: !include json/schema/sjp.events.employer-deleted.json
        example: !include json/sjp.events.employer-deleted.json

      application/vnd.sjp.events.employment-status-updated+json:
        schema: !include json/schema/sjp.events.employment-status-updated.json
        example: !include json/sjp.events.employment-status-updated.json

      application/vnd.sjp.events.defendant-national-insurance-number-updated+json:
        schema: !include json/schema/sjp.events.defendant-national-insurance-number-updated.json
        example: !include json/sjp.events.defendant-national-insurance-number-updated.json

      application/vnd.sjp.events.interpreter-for-defendant-updated+json:
        schema: !include json/schema/sjp.events.interpreter-for-defendant-updated.json
        example: !include json/sjp.events.interpreter-for-defendant-updated.json

      application/vnd.sjp.events.interpreter-for-defendant-cancelled+json:
        schema: !include json/schema/sjp.events.interpreter-for-defendant-cancelled.json
        example: !include json/sjp.events.interpreter-for-defendant-cancelled.json

      application/vnd.sjp.events.all-offences-withdrawal-requested+json:
        schema: !include json/schema/sjp.events.all-offences-withdrawal-requested.json
        example: !include json/sjp.events.all-offences-withdrawal-requested.json

      application/vnd.sjp.events.all-offences-withdrawal-request-cancelled+json:
        schema: !include json/schema/sjp.events.all-offences-withdrawal-request-cancelled.json
        example: !include json/sjp.events.all-offences-withdrawal-request-cancelled.json

      application/vnd.sjp.events.case-reopened-in-libra+json:
        schema: !include json/schema/sjp.events.case-reopened-in-libra.json
        example: !include json/sjp.events.case-reopened-in-libra.json

      application/vnd.sjp.events.case-reopened-in-libra-updated+json:
        schema: !include json/schema/sjp.events.case-reopened-in-libra-updated.json
        example: !include json/sjp.events.case-reopened-in-libra.json

      application/vnd.sjp.events.case-reopened-in-libra-undone+json:
        schema: !include json/schema/sjp.events.case-reopened-in-libra-undone.json
        example: !include json/sjp.events.case-reopened-in-libra-undone.json

      application/vnd.sjp.events.enterprise-id-associated+json:
        schema: !include json/schema/sjp.events.enterprise-id-associated.json
        example: !include json/sjp.events.enterprise-id-associated.json

      application/vnd.sjp.events.offences-for-defendant-updated+json:
        schema: !include json/schema/sjp.events.offences-for-defendant-updated.json
        example: !include json/sjp.events.offences-for-defendant-updated.json

      application/vnd.sjp.events.case-assigned+json:
        schema: !include json/schema/sjp.events.case-assigned.json
        example: !include json/sjp.events.case-assigned.json

      application/vnd.sjp.events.case-assignment-deleted+json:
        schema: !include json/schema/sjp.events.case-assignment-deleted.json
        example: !include json/sjp.events.case-assignment-deleted.json

      application/vnd.sjp.events.defendant-details-updated+json:
        schema: !include json/schema/sjp.events.defendant-details-updated.json
        example: !include json/sjp.events.defendant-details-updated.json

      application/vnd.sjp.events.defendant-details-moved-from-people+json:
        schema: !include json/schema/sjp.events.defendant-details-moved-from-people.json
        example: !include json/sjp.events.defendant-details-moved-from-people.json

      application/vnd.sjp.events.trial-requested+json:
        schema: !include json/schema/sjp.events.trial-requested.json
        example: !include json/sjp.events.trial-requested.json

      application/vnd.sjp.events.trial-request-cancelled+json:
        schema: !include json/schema/sjp.events.trial-request-cancelled.json
        example: !include json/sjp.events.trial-request-cancelled.json

      application/vnd.sjp.events.defendant-address-updated+json:
        schema: !include json/schema/sjp.events.defendant-address-updated.json
        example: !include json/sjp.events.defendant-address-updated.json

      application/vnd.sjp.events.defendant-date-of-birth-updated+json:
        schema: !include json/schema/sjp.events.defendant-date-of-birth-updated.json
        example: !include json/sjp.events.defendant-date-of-birth-updated.json

      application/vnd.sjp.events.defendant-personal-name-updated+json:
        schema: !include json/schema/sjp.events.defendant-personal-name-updated.json
        example: !include json/sjp.events.defendant-personal-name-updated.json

      application/vnd.sjp.events.online-plea-received+json:
        schema: !include json/schema/sjp.events.online-plea-received.json
        example: !include json/sjp.events.online-plea-received.json

      application/vnd.sjp.events.magistrate-session-started+json:
        schema: !include json/schema/sjp.events.magistrate-session-started.json
        example: !include json/sjp.events.magistrate-session-started.json

      application/vnd.sjp.events.delegated-powers-session-started+json:
        schema: !include json/schema/sjp.events.delegated-powers-session-started.json
        example: !include json/sjp.events.delegated-powers-session-started.json

      application/vnd.sjp.events.magistrate-session-ended+json:
        schema: !include json/schema/sjp.events.magistrate-session-ended.json
        example: !include json/sjp.events.magistrate-session-ended.json

      application/vnd.sjp.events.delegated-powers-session-ended+json:
        schema: !include json/schema/sjp.events.delegated-powers-session-ended.json
        example: !include json/sjp.events.delegated-powers-session-ended.json

      application/vnd.sjp.events.case-marked-ready-for-decision+json:
        schema: !include json/schema/sjp.events.case-marked-ready-for-decision.json
        example: !include json/sjp.events.case-marked-ready-for-decision.json

      application/vnd.sjp.events.case-unmarked-ready-for-decision+json:
        schema: !include json/schema/sjp.events.case-unmarked-ready-for-decision.json
        example: !include json/sjp.events.case-unmarked-ready-for-decision.json

      application/vnd.sjp.events.dates-to-avoid-received+json:
        schema: !include json/schema/sjp.events.dates-to-avoid-received.json
        example: !include json/sjp.events.dates-to-avoid-received.json