#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/listener/message/structure

version: v1
/structure.event:
  post:
    body:
      application/vnd.structure.events.defendant-added+json:
          schema: !include json/schema/structure.events.defendant-added.json
          example: !include json/structure.events.defendant-added.json

      application/vnd.structure.events.storage-reference-set+json:
        schema: !include json/schema/structure.events.storage-reference-set.json
        example: !include json/structure.events.storage-reference-set.json

      application/vnd.structure.events.case-document-added+json:
        schema: !include json/schema/structure.events.case-document-added.json
        example: !include json/structure.events.case-document-added.json

      application/vnd.structure.events.case-created+json:
        schema: !include json/schema/structure.events.case-created.json
        example: !include json/structure.events.case-created.json

      application/vnd.structure.events.sjp-case-created+json:
        example: !include json/structure.events.sjp-case-created.json
        schema: !include json/schema/structure.events.sjp-case-created.json

      application/vnd.structure.events.plea-updated+json:
        schema: !include json/schema/structure.events.plea-updated.json
        example: !include json/structure.events.plea-updated.json

      application/vnd.structure.events.plea-cancelled+json:
        schema: !include json/schema/structure.events.plea-cancelled.json
        example: !include json/structure.events.plea-cancelled.json

      application/vnd.structure.events.case-completed+json:
        schema: !include json/schema/structure.events.case-completed.json
        example: !include json/structure.events.case-completed.json

      application/vnd.structure.events.person-type-updated+json:
        schema: !include json/schema/structure.events.person-type-updated.json
        example: !include json/structure.events.person-type-updated.json

      application/vnd.structure.events.court-referral-created+json:
        schema: !include json/schema/structure.events.court-referral-created.json
        example: !include json/structure.events.court-referral-created.json

      application/vnd.structure.events.court-referral-actioned+json:
        schema: !include json/schema/structure.events.court-referral-actioned.json
        example: !include json/structure.events.court-referral-actioned.json

      application/vnd.structure.events.financial-means-updated+json:
        schema: !include json/schema/structure.events.financial-means-updated.json
        example: !include json/structure.events.financial-means-updated.json

      application/vnd.structure.events.employer-updated+json:
        schema: !include json/schema/structure.events.employer-updated.json
        example: !include json/structure.events.employer-updated.json

      application/vnd.structure.events.interpreter-for-defendant-updated+json:
        schema: !include json/schema/structure.events.interpreter-for-defendant-updated.json
        example: !include json/structure.events.interpreter-for-defendant-updated.json

      application/vnd.structure.events.interpreter-for-defendant-cancelled+json:
        schema: !include json/schema/structure.events.interpreter-for-defendant-cancelled.json
        example: !include json/structure.events.interpreter-for-defendant-cancelled.json

      application/vnd.structure.events.all-offences-withdrawal-requested+json:
        schema: !include json/schema/structure.events.all-offences-withdrawal-requested.json
        example: !include json/structure.events.all-offences-withdrawal-requested.json

      application/vnd.structure.events.all-offences-withdrawal-request-cancelled+json:
        schema: !include json/schema/structure.events.all-offences-withdrawal-request-cancelled.json
        example: !include json/structure.events.all-offences-withdrawal-request-cancelled.json

      application/vnd.structure.events.case-reopened-in-libra+json:
        schema: !include json/schema/structure.events.case-reopened-in-libra.json
        example: !include json/structure.events.case-reopened-in-libra.json

      application/vnd.structure.events.case-reopened-in-libra-updated+json:
        schema: !include json/schema/structure.events.case-reopened-in-libra-updated.json
        example: !include json/structure.events.case-reopened-in-libra.json

      application/vnd.structure.events.case-reopened-in-libra-undone+json:
        schema: !include json/schema/structure.events.case-reopened-in-libra-undone.json
        example: !include json/structure.events.case-reopened-in-libra-undone.json

      application/vnd.structure.events.enterprise-id-associated+json:
        schema: !include json/schema/structure.events.enterprise-id-associated.json
        example: !include json/structure.events.enterprise-id-associated.json

      application/vnd.structure.events.person-info-added+json:
        schema: !include json/schema/structure.events.person-info-added.json
        example: !include json/structure.events.person-info-added.json

      application/vnd.structure.events.person-info-updated+json:
        schema: !include json/schema/structure.events.person-info-updated.json
        example: !include json/structure.events.person-info-updated.json

      application/vnd.structure.events.offences-for-defendant-updated+json:
        schema: !include json/schema/structure.events.offences-for-defendant-updated.json
        example: !include json/structure.events.offences-for-defendant-updated.json
