#ARG base_image=crmdvrepo01.azurecr.io/wildfly:310122

FROM {base_image}

ARG version
ARG repo_loc=https://libraries-internal.mdv.cpp.nonlive/artifactory/repocentral
ARG framework_version=8.0.4
ARG eventstore_version=8.2.2
ARG activiti_version=5.22.0
ARG wildfly_home=/opt/wildfly
ARG wildfly_user=wildfly

# service war file
ADD ${repo_loc}/uk/gov/moj/cpp/sjp/sjp-service/${version}/sjp-service-${version}.war ${wildfly_home}/standalone/deployments/
USER root
RUN chown ${wildfly_user}:${wildfly_user} ${wildfly_home}/standalone/deployments/sjp-service-${version}.war

# liquibase jars & config
RUN mkdir /tmp/liquibase
ADD ${repo_loc}/uk/gov/moj/cpp/sjp/sjp-viewstore-liquibase/${version}/sjp-viewstore-liquibase-${version}.jar /tmp/liquibase/sjp-viewstore-liquibase.jar
ADD ${repo_loc}/uk/gov/justice/event-store/event-repository-liquibase/${eventstore_version}/event-repository-liquibase-${eventstore_version}.jar  /tmp/liquibase/event-repository-liquibase.jar
ADD ${repo_loc}/uk/gov/justice/event-store/aggregate-snapshot-repository-liquibase/${eventstore_version}/aggregate-snapshot-repository-liquibase-${eventstore_version}.jar  /tmp/liquibase/aggregate-snapshot-repository-liquibase.jar
ADD ${repo_loc}/uk/gov/justice/event-store/event-buffer-liquibase/${eventstore_version}/event-buffer-liquibase-${eventstore_version}.jar  /tmp/liquibase/event-buffer-liquibase.jar
ADD ${repo_loc}/uk/gov/justice/event-store/event-tracking-liquibase/${eventstore_version}/event-tracking-liquibase-${eventstore_version}.jar  /tmp/liquibase/event-tracking-liquibase.jar
ADD ${repo_loc}/uk/gov/justice/services/framework-system-liquibase/${framework_version}/framework-system-liquibase-${framework_version}.jar  /tmp/liquibase/framework-system-liquibase.jar
ADD ${repo_loc}/uk/gov/moj/cpp/activiti/activiti-liquibase/${activiti_version}/activiti-liquibase-${activiti_version}.jar  /tmp/liquibase/activiti-liquibase.jar
RUN chmod -R 755 /tmp/liquibase
COPY scripts/liquibase.sh /tmp/liquibase/liquibase.sh
RUN chown ${wildfly_user}:${wildfly_user} /tmp/liquibase/liquibase.sh && chmod 755 /tmp/liquibase/liquibase.sh
RUN mkdir /opt/cpp-tools
ADD ${repo_loc}/uk/gov/justice/services/framework-jmx-command-client/${framework_version}/framework-jmx-command-client-${framework_version}.jar /opt/cpp-tools/framework-jmx-command-client.jar
RUN chown ${wildfly_user}:${wildfly_user} /opt/cpp-tools/framework-jmx-command-client.jar && chmod 755 /opt/cpp-tools/framework-jmx-command-client.jar
USER ${wildfly_user}
LABEL base_image {base_image}