package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;

rule "sjp.query.case"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.case");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.case-by-urn"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.case-by-urn");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.financial-means"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.financial-means");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.employer"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.employer");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.case-documents"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.case-documents");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.case-defendants"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.case-defendants");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.case-by-urn-postcode"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.case-by-urn-postcode");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.cases-search-by-material-id"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.cases-search-by-material-id");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.cases-search"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.cases-search");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.case-search-results"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.case-search-results");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.cases-missing-sjpn"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.cases-missing-sjpn");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.cases-missing-sjpn-with-details"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.cases-missing-sjpn-with-details");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.awaiting-cases"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.awaiting-cases");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.cases-referred-to-court"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.cases-referred-to-court");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.not-ready-cases-grouped-by-age"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.not-ready-cases-grouped-by-age");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.oldest-case-age"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.oldest-case-age");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.result-orders"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.result-orders");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.defendants-online-plea"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.defendants-online-plea");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.pending-dates-to-avoid"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.pending-dates-to-avoid");
  then
    $outcome.setSuccess(true);
end

rule "sjp.query.session"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.query.session");
  then
    $outcome.setSuccess(true);
end
