#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/processor/message/sjp

/public.event:
  get:
      responses:
          200:
              body:
                  application/vnd.public.sjp.case-started+json:
                      schema: !include json/schema/public.sjp.case-started.json
                      example: !include json/public.sjp.case-started.json
                  application/vnd.public.sjp.sjp-case-created+json:
                      schema: !include json/schema/public.sjp.sjp-case-created.json
                      example: !include json/public.sjp.sjp-case-created.json
                  application/vnd.public.sjp.case-creation-failed-because-case-already-existed+json:
                      schema: !include json/schema/public.sjp.case-creation-failed-because-case-already-existed.json
                      example: !include json/public.sjp.case-creation-failed-because-case-already-existed.json
                  application/vnd.public.sjp.all-offences-withdrawal-requested+json:
                      schema: !include json/schema/public.sjp.all-offences-withdrawal-requested.json
                      example: !include json/public.sjp.all-offences-withdrawal-requested.json
                  application/vnd.public.sjp.all-offences-withdrawal-request-cancelled+json:
                      schema: !include json/schema/public.sjp.all-offences-withdrawal-request-cancelled.json
                      example: !include json/public.sjp.all-offences-withdrawal-request-cancelled.json
                  application/vnd.public.sjp.case-document-added+json:
                      schema: !include json/schema/public.sjp.case-document-added.json
                      example: !include json/public.sjp.case-document-added.json
                  application/vnd.public.sjp.case-document-already-exists+json:
                      schema: !include json/schema/public.sjp.case-document-already-exists.json
                      example: !include json/public.sjp.case-document-already-exists.json
                  application/vnd.public.sjp.case-created+json:
                      schema: !include json/schema/public.sjp.case-created.json
                      example: !include json/public.sjp.case-created.json
                  application/vnd.public.sjp.case-update-rejected+json:
                      schema: !include json/schema/public.sjp.case-update-rejected.json
                      example: !include json/public.sjp.case-update-rejected.json
                  application/vnd.public.sjp.case-reopened-in-libra+json:
                      schema: !include json/schema/public.sjp.case-reopened-in-libra.json
                      example: !include json/public.sjp.case-reopened-in-libra.json
                  application/vnd.public.sjp.case-reopened-in-libra-updated+json:
                      schema: !include json/schema/public.sjp.case-reopened-in-libra-updated.json
                      example: !include json/public.sjp.case-reopened-in-libra.json
                  application/vnd.public.sjp.case-reopened-in-libra-undone+json:
                      schema: !include json/schema/public.sjp.case-reopened-in-libra-undone.json
                      example: !include json/public.sjp.case-reopened-in-libra-undone.json
                  application/vnd.public.sjp.plea-updated+json:
                      schema: !include json/schema/public.sjp.plea-updated.json
                      example: !include json/public.sjp.plea-updated.json
                  application/vnd.public.sjp.plea-cancelled+json:
                      schema: !include json/schema/public.sjp.plea-cancelled.json
                      example: !include json/public.sjp.plea-cancelled.json
                  application/vnd.public.sjp.enterprise-id-associated+json:
                      schema: !include json/schema/public.sjp.enterprise-id-associated.json
                      example: !include json/public.sjp.enterprise-id-associated.json
                  application/vnd.public.sjp.case-document-uploaded+json:
                      schema: !include json/schema/public.sjp.case-document-uploaded.json
                      example: !include json/public.sjp.case-document-uploaded.json
                  application/vnd.public.sjp.financial-means-updated+json:
                      schema: !include json/schema/public.sjp.financial-means-updated.json
                      example: !include json/public.sjp.financial-means-updated.json
                  application/vnd.public.sjp.employer-updated+json:
                      schema: !include json/schema/public.sjp.employer-updated.json
                      example: !include json/public.sjp.employer-updated.json
                  application/vnd.public.sjp.employer-deleted+json:
                      schema: !include json/schema/public.sjp.employer-deleted.json
                      example: !include json/public.sjp.employer-deleted.json
                  application/vnd.public.sjp.events.offences-for-defendant-updated+json:
                       schema: !include json/schema/public.sjp.events.offences-for-defendant-updated.json
                       example: !include json/public.sjp.events.offences-for-defendant-updated.json
                  application/vnd.public.sjp.events.defendant-offences-does-not-have-required-modeoftrial+json:
                       schema: !include json/schema/public.sjp.events.defendant-offences-does-not-have-required-modeoftrial.json
                       example: !include json/public.sjp.events.defendant-offences-does-not-have-required-modeoftrial.json
                  application/vnd.public.sjp.court-referral-actioned+json:
                      schema: !include json/schema/public.sjp.court-referral-actioned.json
                      example: !include json/public.sjp.court-referral-actioned.json
                  application/vnd.public.sjp.events.defendant-details-updated+json: !!null
