#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/processor/message/sjp

/sjp.event:
  post:
    body:
      application/vnd.sjp.events.case-started+json:
          schema: !include json/schema/sjp.events.case-started.json
          example: !include json/sjp.events.case-started.json
      application/vnd.sjp.events.all-offences-withdrawal-requested+json:
          schema: !include json/schema/sjp.events.all-offences-withdrawal-requested.json
          example: !include json/sjp.events.all-offences-withdrawal-requested.json
      application/vnd.sjp.events.all-offences-withdrawal-request-cancelled+json:
          schema: !include json/schema/sjp.events.all-offences-withdrawal-request-cancelled.json
          example: !include json/sjp.events.all-offences-withdrawal-request-cancelled.json
      application/vnd.sjp.events.case-creation-failed-because-case-already-existed+json:
          schema: !include json/schema/sjp.events.case-creation-failed-because-case-already-existed.json
          example: !include json/sjp.events.case-creation-failed-because-case-already-existed.json
      application/vnd.sjp.events.case-document-uploaded+json:
          schema: !include json/schema/sjp.events.case-document-uploaded.json
          example: !include json/sjp.events.case-document-uploaded.json
      application/vnd.sjp.events.case-document-added+json:
          schema: !include json/schema/sjp.events.case-document-added.json
          example: !include json/sjp.events.case-document-added.json
      application/vnd.sjp.events.case-document-already-exists+json:
          schema: !include json/schema/sjp.events.case-document-already-exists.json
          example: !include json/sjp.events.case-document-already-exists.json
      application/vnd.sjp.events.case-update-rejected+json:
          schema: !include json/schema/sjp.events.case-update-rejected.json
          example: !include json/sjp.events.case-update-rejected.json
      application/vnd.sjp.events.case-reopened-in-libra+json:
        schema: !include json/schema/sjp.events.case-reopened-in-libra.json
        example: !include json/sjp.events.case-reopened-in-libra.json
      application/vnd.sjp.events.case-reopened-in-libra-updated+json:
        schema: !include json/schema/sjp.events.case-reopened-in-libra-updated.json
        example: !include json/sjp.events.case-reopened-in-libra.json
      application/vnd.sjp.events.case-reopened-in-libra-undone+json:
        schema: !include json/schema/sjp.events.case-reopened-in-libra-undone.json
        example: !include json/sjp.events.case-reopened-in-libra-undone.json
      application/vnd.sjp.events.plea-updated+json:
          schema: !include json/schema/sjp.events.plea-updated.json
          example: !include json/sjp.events.plea-updated.json
      application/vnd.sjp.events.plea-cancelled+json:
          schema: !include json/schema/sjp.events.plea-cancelled.json
          example: !include json/sjp.events.plea-cancelled.json
      application/vnd.sjp.events.enterprise-id-associated+json:
          schema: !include json/schema/sjp.events.enterprise-id-associated.json
          example: !include json/sjp.events.enterprise-id-associated.json
      application/vnd.sjp.events.undo-case-reopened-failed+json:
          schema: !include json/schema/sjp.events.undo-case-reopened-failed.json
          example: !include json/sjp.events.undo-case-reopened-failed.json
      application/vnd.sjp.events.financial-means-updated+json:
        schema: !include json/schema/sjp.events.financial-means-updated.json
        example: !include json/sjp.events.financial-means-updated.json
      application/vnd.sjp.events.employer-updated+json:
        schema: !include json/schema/sjp.events.employer-updated.json
        example: !include json/sjp.events.employer-updated.json
      application/vnd.sjp.events.employer-deleted+json:
        schema: !include json/schema/sjp.events.employer-deleted.json
        example: !include json/sjp.events.employer-deleted.json
      application/vnd.sjp.events.offences-for-defendant-updated+json:
        schema: !include json/schema/sjp.events.offences-for-defendant-updated.json
        example: !include json/sjp.events.offences-for-defendant-updated.json
      application/vnd.sjp.events.defendant-offences-does-not-have-required-modeoftrial+json:
        schema: !include json/schema/sjp.events.defendant-offences-does-not-have-required-modeoftrial.json
        example: !include json/sjp.events.defendant-offences-does-not-have-required-modeoftrial.json
      application/vnd.sjp.events.defendant-details-updated+json:
        schema: !include json/schema/sjp.events.defendant-details-updated.json
        example: !include json/sjp.events.defendant-details-updated.json
      application/vnd.sjp.events.court-referral-actioned+json:
        schema: !include json/schema/sjp.events.court-referral-actioned.json
        example: !include json/sjp.events.court-referral-actioned.json
      application/vnd.sjp.events.case-received+json:
        example: !include json/sjp.events.case-received.json
        schema: !include json/schema/sjp.events.case-received.json



/public.event:
  post:
    body:
      application/vnd.public.resulting.referenced-decisions-saved+json:
          schema: !include json/schema/public.resulting.referenced-decisions-saved.json
          example: !include json/public.resulting.referenced-decisions-saved.json
      application/vnd.public.resulting.case-referred-to-court+json:
          schema: !include json/schema/public.resulting.case-referred-to-court.json
          example: !include json/public.resulting.case-referred-to-court.json
      application/vnd.material.material-added+json:
          schema: !include json/schema/material.material-added.json
          example: !include json/material.material-added.json
      application/vnd.assignment.assignment-created+json:
        schema: !include json/schema/assignment.assignment-created.json
        example: !include json/assignment.assignment-created.json
      application/vnd.assignment.assignment-deleted+json:
        schema: !include json/schema/assignment.assignment-deleted.json
        example: !include json/assignment.assignment-deleted.json
