#%RAML 0.8
title: Sjp Query
version: v0.1
protocols: [ HTTP, HTTPS ]

baseUri: http://localhost:8080/sjp-query-controller/query/controller/rest/sjp

/cases/{caseId}:
  description: return a case
  uriParameters:
    caseId:
      description: Case ID
      type: string
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.sjp.query.case+json
          name: sjp.query.case
      ...
    responses:
      200:
        body:
          application/vnd.sjp.query.case+json:
            schema: !include json/schema/sjp.query.case.json
            example: !include json/sjp.query.case.json

/cases:
  get:
    description: |
      Get case by URN
      ...
      (mapping):
          responseType: application/vnd.sjp.query.case-by-urn+json
          name: sjp.query.case-by-urn

      ...
    queryParameters:
      urn:
        description: URN
        type: string
        required: false
    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.case-by-urn+json:
                  schema: !include json/schema/sjp.query.case.json
                  example: !include json/sjp.query.case.json

/result-orders:
  get:
    description: |
      Get cases with order.
      ...
      (mapping):
          responseType: application/vnd.sjp.query.result-orders+json
          name: sjp.query.result-orders
      ...
    queryParameters:
      fromDate:
          description: From date inclusive.
          type: string
          required: true
      toDate:
          description: To date exclusive.
          type: string
          required: true

    responses:
      200:
        body:
          application/vnd.sjp.query.result-orders+json:
            schema: !include json/schema/sjp.query.result-orders.json
            example: !include json/sjp.query.result-orders.json

/cases-missing-sjpn:
  get:
    description: |
      Get cases missing the SJPN
      ...
      (mapping):
          responseType: application/vnd.sjp.query.cases-missing-sjpn+json
          name: sjp.query.cases-missing-sjpn
      ...
    queryParameters:
      limit:
        description: |
          Limits the number of case IDs returned. Set to 0 if you only need the number of cases.
        type: integer
        required: false
      daysSincePosting:
        description: |
          Returns cases that has posting date older than daysSincePosting.
        type: integer
        required: false

    responses:
      200:
        body:
          application/vnd.sjp.query.cases-missing-sjpn+json:
            schema: !include json/schema/sjp.query.cases-missing-sjpn.json
            example: !include json/sjp.query.cases-missing-sjpn.json

/cases-missing-sjpn-with-details:
  get:
    description: |
      Get cases missing the SJPN with defendant details
      ...
      (mapping):
          responseType: application/vnd.sjp.query.cases-missing-sjpn-with-details+json
          name: sjp.query.cases-missing-sjpn-with-details
      ...
    queryParameters:
      daysSincePosting:
        description: |
          Returns cases that has posting date older than daysSincePosting.
        type: integer
        required: false

    responses:
      200:
        body:
          application/vnd.sjp.query.cases-missing-sjpn-with-details+json:
            schema: !include json/schema/sjp.query.cases-missing-sjpn-with-details.json
            example: !include json/sjp.query.cases-missing-sjpn-with-details.json

/defendant/{defendantId}/financial-means:
  uriParameters:
    defendantId:
      description: The ID of the defendant
      type: string
  get:
    description: |
      Retrieve financial means information
      ...
      (mapping):
          responseType: application/vnd.sjp.query.financial-means+json
          name: sjp.query.financial-means
      ...
    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.financial-means+json:
                  schema: !include json/schema/sjp.query.financial-means.json
                  example: !include json/sjp.query.financial-means.json

/defendant/{defendantId}/employer:
  uriParameters:
    defendantId:
      description: The ID of the defendant
      type: string
  get:
    description: |
      Retrieve employer information
      ...
      (mapping):
          responseType: application/vnd.sjp.query.employer+json
          name: sjp.query.employer
      ...
    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.employer+json:
                  schema: !include json/schema/sjp.query.employer.json
                  example: !include json/sjp.query.employer.json

/search:
  get:
    description: |
      Search for cases
      ...
      (mapping):
          responseType: application/vnd.sjp.query.cases-search-by-material-id+json
          name: sjp.query.cases-search-by-material-id

      (mapping):
          responseType: application/vnd.sjp.query.case-search-results+json
          name: sjp.query.case-search-results


      ...
    queryParameters:
      q:
        description: query
        type: string
    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.cases-search-by-material-id+json:
                  schema: !include json/schema/sjp.query.cases-search-by-material-id.json
                  example: !include json/sjp.query.cases-search-by-material-id.json

                application/vnd.sjp.query.case-search-results+json:
                  schema: !include json/schema/sjp.query.case-search-results.json
                  example: !include json/sjp.query.case-search-results.json

/cases/{caseId}/documents:
  description: Get list of case documents for a corresponding case
  uriParameters:
    caseId:
      description: Case ID
      type: string
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.sjp.query.case-documents+json
          name: sjp.query.case-documents
      ...
    responses:
      200:
        body:
          application/vnd.sjp.query.case-documents+json:
            schema: !include json/schema/sjp.query.case-documents.json
            example: !include json/sjp.query.case-documents.json

/cases/awaiting:
  description: return the 600 oldest not resulted SJP cases, that have SJPN documents
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.sjp.query.awaiting-cases+json
          name: sjp.query.awaiting-cases
      ...
    responses:
      200:
        body:
          application/vnd.sjp.query.awaiting-cases+json:
            schema: !include json/schema/sjp.query.awaiting-cases.json
            example: !include json/sjp.query.awaiting-cases.json

/cases/referred-to-court:
  description: return the SJP cases which have been referred to court
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.sjp.query.cases-referred-to-court+json
          name: sjp.query.cases-referred-to-court
      ...
    responses:
      200:
        body:
          application/vnd.sjp.query.cases-referred-to-court+json:
            schema: !include json/schema/sjp.query.cases-referred-to-court.json
            example: !include json/sjp.query.cases-referred-to-court.json

/cases/not-ready-grouped-by-age:
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.sjp.query.not-ready-cases-grouped-by-age+json
          name: sjp.query.not-ready-cases-grouped-by-age
      ...
    responses:
      200:
        body:
          application/vnd.sjp.query.not-ready-cases-grouped-by-age+json:
            schema: !include json/schema/sjp.query.not-ready-cases-grouped-by-age.json
            example: !include json/sjp.query.not-ready-cases-grouped-by-age.json

/cases/oldest-age:
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.sjp.query.oldest-case-age+json
          name: sjp.query.oldest-case-age
      ...
    responses:
      200:
        body:
          application/vnd.sjp.query.oldest-case-age+json:
            schema: !include json/schema/sjp.query.oldest-case-age.json
            example: !include json/sjp.query.oldest-case-age.json

/cases-for-citizen:
  get:
    description: |
      Get case by URN and postcode
      ...
      (mapping):
          responseType: application/vnd.sjp.query.case-by-urn-postcode+json
          name: sjp.query.case-by-urn-postcode
      ...
    queryParameters:
      urn:
        description: URN
        type: string
        required: true
      postcode:
        description: Postcode
        type: string
        required: true

    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.case-by-urn-postcode+json:
                  schema: !include json/schema/sjp.query.case-by-urn-postcode.json
                  example: !include json/sjp.query.case-by-urn-postcode.json

/cases/{caseId}/defendants-online-plea:
  get:
    description: |
      Get defendant's online plea on a case.
      ...
      (mapping):
          responseType: application/vnd.sjp.query.defendants-online-plea+json
          name: sjp.query.defendants-online-plea
      ...
    queryParameters:
    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.defendants-online-plea+json:
                  schema: !include json/schema/sjp.query.defendants-online-plea.json
                  example: !include json/sjp.query.defendants-online-plea.json

/cases/pending-dates-to-avoid:
  get:
    description: |
      Get all cases that are pending submission (from the prosecutor) of any dates-to-avoid for the case's trial.
      ...
      (mapping):
          responseType: application/vnd.sjp.query.pending-dates-to-avoid+json
          name: sjp.query.pending-dates-to-avoid
      ...
    queryParameters:
    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.pending-dates-to-avoid+json:
                  schema: !include json/schema/sjp.query.pending-dates-to-avoid.json
                  example: !include json/sjp.query.pending-dates-to-avoid.json


/cases/ready-cases-reasons-counts:
  get:
    description: |
      Get count of ready cases grouped by reason
      ...
      (mapping):
          responseType: application/vnd.sjp.query.ready-cases-reasons-counts+json
          name: sjp.query.ready-cases-reasons-counts
      ...
    responses:
      200:
        body:
          application/vnd.sjp.query.ready-cases-reasons-counts+json:
            schema: !include json/schema/sjp.query.ready-cases-reasons-counts.json
            example: !include json/sjp.query.ready-cases-reasons-counts.json

/sessions/{sessionId}:
  get:
    description: |
      Get session.
      ...
      (mapping):
          responseType: application/vnd.sjp.query.session+json
          name: sjp.query.session
      ...
    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.session+json:
                  schema: !include json/schema/sjp.query.session.json
                  example: !include json/sjp.query.session.json
