#%RAML 0.8
title: Sjp Query
version: v0.1
protocols: [ HTTP, HTTPS ]

baseUri: http://localhost:8080/sjp-query-view/query/view/rest/sjp

/cases/{caseId}:
  description: return a case
  uriParameters:
    caseId:
      description: Case ID
      type: string
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.sjp.query.case+json
          name: sjp.query.case
      (mapping):
          responseType: application/vnd.sjp.query.case-filter-other-and-financial-means-documents+json
          name: sjp.query.case-filter-other-and-financial-means-documents
      ...
    responses:
      200:
        body:
          application/vnd.sjp.query.case+json:
            schema: !include json/schema/sjp.query.case-details.json
            example: !include json/sjp.query.case-details.json
          application/vnd.sjp.query.case-filter-other-and-financial-means-documents+json:
            schema: !include json/schema/sjp.query.case-filter-other-and-financial-means-documents.json
            example: !include json/sjp.query.case-filter-other-and-financial-means-documents.json

/cases:
  get:
    description: |
      Get case by URN
      ...
      (mapping):
          responseType: application/vnd.sjp.query.case-by-urn+json
          name: sjp.query.case-by-urn
      ...
    queryParameters:
      urn:
        description: Unique Reference Number
        type: string
        required: false
    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.case-by-urn+json:
                  schema: !include json/schema/sjp.query.case-details.json
                  example: !include json/sjp.query.case-details.json

/result-orders:
  get:
    description: |
      Get cases with order.
      ...
      (mapping):
          responseType: application/vnd.sjp.query.result-orders+json
          name: sjp.query.result-orders
      ...
    queryParameters:
      fromDate:
          description: From date inclusive.
          type: string
          required: true
      toDate:
          description: To date exclusive.
          type: string
          required: true

    responses:
      200:
        body:
          application/vnd.sjp.query.result-orders+json:
            schema: !include json/schema/sjp.query.result-orders.json
            example: !include json/sjp.query.result-orders.json

/cases-missing-sjpn:
  get:
    description: |
      Get cases missing the SJPN
      ...
      (mapping):
          responseType: application/vnd.sjp.query.cases-missing-sjpn+json
          name: sjp.query.cases-missing-sjpn
      ...
    queryParameters:
      limit:
        description: |
          Limits the number of case IDs returned. Set to 0 if you only need the number of cases.
        type: integer
        required: false
      daysSincePosting:
        description: |
          Returns cases that has posting date older than daysSincePosting.
        type: integer
        required: false

    responses:
      200:
        body:
          application/vnd.sjp.query.cases-missing-sjpn+json:
            schema: !include json/schema/sjp.query.cases-missing-sjpn.json
            example: !include json/sjp.query.cases-missing-sjpn.json

/defendant-details-updates:
  get:
    description: |
      Retrieves the unacknowledged defendant detail updates
      ...
      (mapping):
          responseType: application/vnd.sjp.query.defendant-details-updates+json
          name: sjp.query.defendant-details-updates
      ...
    queryParameters:
      limit:
        description: |
          Defines the number of updates to be returned.
        type: integer
        required: true

    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.defendant-details-updates+json:
                  schema: !include json/schema/sjp.query.defendant-details-updates.json
                  example: !include json/sjp.query.defendant-details-updates.json

/defendant/{defendantId}/financial-means:
  uriParameters:
    defendantId:
      description: The ID of the defendant
      type: string
  get:
    description: |
      Retrieve financial means information
      ...
      (mapping):
          responseType: application/vnd.sjp.query.financial-means+json
          name: sjp.query.financial-means
      ...
    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.financial-means+json:
                  schema: !include json/schema/sjp.query.financial-means.json
                  example: !include json/sjp.query.financial-means.json

/defendant/{defendantId}/employer:
  uriParameters:
    defendantId:
      description: The ID of the defendant
      type: string
  get:
    description: |
      Retrieve employer information
      ...
      (mapping):
          responseType: application/vnd.sjp.query.employer+json
          name: sjp.query.employer
      ...
    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.employer+json:
                  schema: !include json/schema/sjp.query.employer.json
                  example: !include json/sjp.query.employer.json

/cases-for-citizen:
  get:
    description: |
      Get case by URN and postcode
      ...
      (mapping):
          responseType: application/vnd.sjp.query.case-by-urn-postcode+json
          name: sjp.query.case-by-urn-postcode
      ...
    queryParameters:
      urn:
        description: Unique Reference Number. Can be without prefix (e.g. TFL) in case-by-urn-postcode
        type: string
        required: true
      postcode:
        description: Postcode. Spaces are ignored
        type: string
        required: true

    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.case-by-urn-postcode+json:
                  schema: !include json/schema/sjp.query.case-by-urn-postcode.json
                  example: !include json/sjp.query.case-by-urn-postcode.json

/search:
  get:
    description: |
      Search for cases
      ...
      (mapping):
      (mapping):
          responseType: application/vnd.sjp.query.cases-search-by-material-id+json
          name: sjp.query.cases-search-by-material-id

      (mapping):
          responseType: application/vnd.sjp.query.case-search-results+json
          name: sjp.query.case-search-results

      ...
    queryParameters:
      q:
        description: query
        type: string
    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.cases-search-by-material-id+json:
                  schema: !include json/schema/sjp.query.cases-search-by-material-id.json
                  example: !include json/sjp.query.cases-search-by-material-id.json
                application/vnd.sjp.query.case-search-results+json:
                  schema: !include json/schema/sjp.query.case-search-results.json
                  example: !include json/sjp.query.case-search-results.json

/cases/{caseId}/documents:
  description: Get list of case documents for a corresponding case
  uriParameters:
    caseId:
      description: Case ID
      type: string
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.sjp.query.case-documents+json
          name: sjp.query.case-documents
      (mapping):
          responseType: application/vnd.sjp.query.case-documents-filter-other-and-financial-means+json
          name: sjp.query.case-documents-filter-other-and-financial-means
      ...
    responses:
      200:
        body:
          application/vnd.sjp.query.case-documents+json:
            schema: !include json/schema/sjp.query.case-documents.json
            example: !include json/sjp.query.case-documents.json
          application/vnd.sjp.query.case-documents-filter-other-and-financial-means+json:
            schema: !include json/schema/sjp.query.case-documents-filter-other-and-financial-means.json
            example: !include json/sjp.query.case-documents-filter-other-and-financial-means.json

/cases/{caseId}/documents/{documentId}:
  description: get case document
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.sjp.query.case-document+json
          name: sjp.query.case-document
      ...
    responses:
      200:
        body:
          application/vnd.sjp.query.case-document+json:
            schema: !include json/schema/sjp.query.case-document.json
            example: !include json/sjp.query.case-document.json

/cases/{caseId}/defendants-online-plea:
  get:
    description: |
      Get defendant's online plea on a case.
      ...
      (mapping):
          responseType: application/vnd.sjp.query.defendants-online-plea+json
          name: sjp.query.defendants-online-plea
      ...
    queryParameters:
    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.defendants-online-plea+json:
                  schema: !include json/schema/sjp.query.defendants-online-plea.json
                  example: !include json/sjp.query.defendants-online-plea.json

/cases/{caseId}/assignment:
  get:
    description: |
      Get case assignment.
      ...
      (mapping):
          responseType: application/vnd.sjp.query.case-assignment+json
          name: sjp.query.case-assignment
      ...
    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.case-assignment+json:
                  schema: !include json/schema/sjp.query.case-assignment.json
                  example: !include json/sjp.query.case-assignment.json

/cases/assignment/candidates/{sessionType}:
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.sjp.query.assignment-candidates+json
          name: sjp.query.assignment-candidates
      ...

    queryParameters:
      prosecutingAuthorities:
        description: comma separated list of prosecuting authorities.
        type: string
      assignmentRule:
        description: if ALLOW then cases which belong to specified prosecuting authorities are allowed to be returned
        enum: [ALLOW, DISALLOW]
        required: true
      limit:
        description: maximum number of assignment candidates
        type: number
        required: true
      assigneeId:
        description: user to whom cases should be assigned, query will return cases assigned to assignee with highest rank
        type: string
        required: true

    responses:
      200:
        body:
          application/vnd.sjp.query.assignment-candidates+json:
            schema: !include json/schema/sjp.query.assignment-candidates.json
            example: !include json/sjp.query.assignment-candidates.json

/cases/pending-dates-to-avoid:
  get:
    description: |
      Get all cases that are pending submission (from the prosecutor) of any dates-to-avoid for the case's trial.
      ...
      (mapping):
          responseType: application/vnd.sjp.query.pending-dates-to-avoid+json
          name: sjp.query.pending-dates-to-avoid
      ...
    queryParameters:
    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.pending-dates-to-avoid+json:
                  schema: !include json/schema/sjp.query.pending-dates-to-avoid.json
                  example: !include json/sjp.query.pending-dates-to-avoid.json

/cases/ready-cases:
  get:
    description: |
      Get ready cases
      ...
      (mapping):
          responseType: application/vnd.sjp.query.ready-cases+json
          name: sjp.query.ready-cases
      ...
    queryParameters:
      assigneeId:
        type: string
        required: false
    responses:
      200:
        body:
          application/vnd.sjp.query.ready-cases+json:
            schema: !include json/schema/sjp.query.ready-cases.json
            example: !include json/sjp.query.ready-cases.json

/sessions/{sessionId}:
  get:
    description: |
      Get session.
      ...
      (mapping):
          responseType: application/vnd.sjp.query.session+json
          name: sjp.query.session
      ...
    responses:
        200:
          description: OK
          body:
                application/vnd.sjp.query.session+json:
                  schema: !include json/schema/sjp.query.session.json
                  example: !include json/sjp.query.session.json

/cases/{caseId}/prosecuting-authority:
  get:
    description: |
      get case prosecuting authority
      ...
      (mapping):
          responseType: application/vnd.sjp.query.case-prosecuting-authority+json
          name: sjp.query.case-prosecuting-authority
      ...
    responses:
      200:
        body:
          application/vnd.sjp.query.case-prosecuting-authority+json:
            schema: !include json/schema/sjp.query.case-prosecuting-authority.json
            example: !include json/sjp.query.case-prosecuting-authority.json
