#%RAML 0.8
title: API Using media type in the URL
baseUri: message://command/handler/message/sjp
version: v1

/sjp.handler.command:
  post:
    body:
      application/vnd.sjp.command.update-financial-means+json:
          schema: !include json/schema/sjp.command.update-financial-means.json
          example: !include json/sjp.command.update-financial-means.json

      application/vnd.sjp.command.delete-defendant-financial-means-information+json:
          schema: !include json/schema/sjp.command.delete-defendant-financial-means-information.json
          example: !include json/sjp.command.delete-defendant-financial-means-information.json

      application/vnd.sjp.command.update-employer+json:
          schema: !include json/schema/sjp.command.update-employer.json
          example: !include json/sjp.command.update-employer.json

      application/vnd.sjp.command.delete-employer+json:
          schema: !include json/schema/sjp.command.delete-employer.json
          example: !include json/sjp.command.delete-employer.json

      application/vnd.sjp.command.add-case-document+json:
          schema: !include json/schema/sjp.command.add-case-document.json
          example: !include json/sjp.command.add-case-document.json

      application/vnd.sjp.command.upload-case-document+json:
          schema: !include json/schema/sjp.command.upload-case-document.json
          example: !include json/sjp.command.upload-case-document.json

      application/vnd.sjp.command.create-sjp-case+json:
          schema: !include json/schema/sjp.command.create-sjp-case.json
          example: !include json/sjp.command.create-sjp-case.json

      application/vnd.sjp.command.plead-online+json:
          schema: !include json/schema/sjp.command.plead-online.json
          example: !include json/sjp.command.plead-online.json

      application/vnd.sjp.command.mark-case-reopened-in-libra+json:
        schema: !include json/schema/sjp.command.mark-case-reopened-in-libra.json
        example: !include json/sjp.command.case-reopened-in-libra.json

      application/vnd.sjp.command.update-case-reopened-in-libra+json:
        schema: !include json/schema/sjp.command.update-case-reopened-in-libra.json
        example: !include json/sjp.command.case-reopened-in-libra.json

      application/vnd.sjp.command.undo-case-reopened-in-libra+json:
        schema: !include json/schema/sjp.command.undo-case-reopened-in-libra.json
        example: !include json/sjp.command.undo-case-reopened-in-libra.json

      application/vnd.sjp.command.update-defendant-details+json:
        schema: !include json/schema/sjp.command.update-defendant-details.json
        example: !include json/sjp.command.update-defendant-details.json

      application/vnd.sjp.command.update-hearing-requirements+json:
        schema: !include json/schema/sjp.command.update-hearing-requirements.json
        example: !include json/sjp.command.update-hearing-requirements.json

      application/vnd.sjp.command.update-defendant-national-insurance-number+json:
        schema: !include json/schema/sjp.command.update-defendant-national-insurance-number.json
        example: !include json/sjp.command.update-defendant-national-insurance-number.json

      application/vnd.sjp.command.start-session+json:
        schema: !include json/schema/sjp.command.start-session.json
        example: !include json/sjp.command.start-session.json

      application/vnd.sjp.command.end-session+json:
        schema: !include json/schema/sjp.command.end-session.json
        example: !include json/sjp.command.end-session.json

      application/vnd.sjp.command.assign-next-case+json:
        schema: !include json/schema/sjp.command.assign-next-case.json
        example: !include json/sjp.command.assign-next-case.json

      application/vnd.sjp.command.assign-case+json:
        schema: !include json/schema/sjp.command.assign-case.json
        example: !include json/sjp.command.assign-case.json

      application/vnd.sjp.command.unassign-case+json:
        schema: !include json/schema/sjp.command.unassign-case.json
        example: !include json/sjp.command.unassign-case.json

      application/vnd.sjp.command.assign-case-from-candidates-list+json:
        schema: !include json/schema/sjp.command.assign-case-from-candidates-list.json
        example: !include json/sjp.command.assign-case-from-candidates-list.json

      application/vnd.sjp.command.mark-case-ready-for-decision+json:
        schema: !include json/schema/sjp.command.mark-case-ready-for-decision.json
        example: !include json/sjp.command.mark-case-ready-for-decision.json

      application/vnd.sjp.command.unmark-case-ready-for-decision+json:
        schema: !include json/schema/sjp.command.unmark-case-ready-for-decision.json
        example: !include json/sjp.command.unmark-case-ready-for-decision.json

      application/vnd.sjp.command.add-dates-to-avoid+json:
        schema: !include json/schema/sjp.command.add-dates-to-avoid.json
        example: !include json/sjp.command.add-dates-to-avoid.json

      application/vnd.sjp.command.acknowledge-defendant-details-updates+json:
        schema: !include json/schema/sjp.command.acknowledge-defendant-details-updates.json
        example: !include json/sjp.command.acknowledge-defendant-details-updates.json

      application/vnd.sjp.command.update-case-listed-in-criminal-courts+json:
        schema: !include json/schema/sjp.command.update-case-listed-in-criminal-courts.json
        example: !include json/sjp.command.update-case-listed-in-criminal-courts.json

      application/vnd.sjp.command.record-case-referral-for-court-hearing-rejection+json:
        schema: !include json/schema/sjp.command.record-case-referral-for-court-hearing-rejection.json
        example: !include json/sjp.command.record-case-referral-for-court-hearing-rejection.json

      application/vnd.sjp.command.record-case-adjourned-to-later-sjp-hearing+json:
        example: !include json/sjp.command.record-case-adjourned-to-later-sjp-hearing.json
        schema:  !include json/schema/sjp.command.record-case-adjourned-to-later-sjp-hearing.json

      application/vnd.sjp.command.record-case-adjournment-to-later-sjp-hearing-elapsed+json:
        example: !include json/sjp.command.record-case-adjournment-to-later-sjp-hearing-elapsed.json
        schema:  !include json/schema/sjp.command.record-case-adjournment-to-later-sjp-hearing-elapsed.json

      application/vnd.sjp.command.store-transparency-report-data+json:
          schema: !include json/schema/sjp.command.store-transparency-report-data.json
          example: !include json/sjp.command.store-transparency-report-data.json

      application/vnd.sjp.command.update-transparency-report-data+json:
          schema: !include json/schema/sjp.command.update-transparency-report-data.json
          example: !include json/sjp.command.update-transparency-report-data.json

      application/vnd.sjp.command.update-press-transparency-report-data+json:
          schema: !include json/schema/sjp.command.update-press-transparency-report-data.json
          example: !include json/sjp.command.update-press-transparency-report-data.json

      application/vnd.sjp.command.store-press-transparency-report-data+json:
          schema: !include json/schema/sjp.command.store-press-transparency-report-data.json
          example: !include json/sjp.command.store-press-transparency-report-data.json

      application/vnd.sjp.command.request-transparency-report+json: !!null

      application/vnd.sjp.command.request-press-transparency-report+json: !!null

      application/vnd.sjp.command.transparency-report-failed+json:
        schema: !include json/schema/sjp.command.transparency-report-failed.json
        example: !include json/sjp.command.transparency-report-failed.json

      application/vnd.sjp.command.press-transparency-report-failed+json:
        schema: !include json/schema/sjp.command.press-transparency-report-failed.json
        example: !include json/sjp.command.press-transparency-report-failed.json

      application/vnd.sjp.command.add-case-note+json:
        example: !include json/sjp.command.add-case-note.json
        schema:  !include json/schema/sjp.command.add-case-note.json

      application/vnd.sjp.command.set-offences-withdrawal-requests-status+json:
        example: !include json/sjp.command.set-offences-withdrawal-requests-status.json
        schema:  !include json/schema/sjp.command.set-offences-withdrawal-requests-status.json

      application/vnd.sjp.command.set-pleas+json:
        example: !include json/sjp.command.set-pleas.json
        schema: !include json/schema/sjp.command.set-pleas.json

      application/vnd.sjp.command.update-all-financial-means+json:
          schema: !include json/schema/sjp.command.update-all-financial-means.json
          example: !include json/sjp.command.update-all-financial-means.json

      application/vnd.sjp.command.save-decision+json:
        example: !include json/sjp.command.save-decision.json
        schema:  !include json/schema/sjp.command.save-decision.json

      application/vnd.sjp.command.expire-defendant-response-timer+json:
        example: !include json/sjp.command.expire-defendant-response-timer.json
        schema:  !include json/schema/sjp.command.expire-defendant-response-timer.json

      application/vnd.sjp.command.expire-dates-to-avoid-timer+json:
        example: !include json/sjp.command.expire-dates-to-avoid-timer.json
        schema:  !include json/schema/sjp.command.expire-dates-to-avoid-timer.json

      application/vnd.sjp.command.add-case-assignment-restriction+json:
        example: !include json/sjp.command.add-case-assignment-restriction.json
        schema:  !include json/schema/sjp.command.add-case-assignment-restriction.json

      application/vnd.sjp.command.set-dates-to-avoid-required+json: !!null

      application/vnd.sjp.command.resolve-case-status+json: !!null

      application/vnd.sjp.command.update-cases-management-status+json:
        example: !include json/sjp.command.update-cases-management-status.json
        schema:  !include json/schema/sjp.command.update-cases-management-status.json

      application/vnd.sjp.command.change-case-management-status+json:
       example: !include json/sjp.command.change-case-management-status.json
       schema:  !include json/schema/sjp.command.change-case-management-status.json

      application/vnd.sjp.command.add-request-for-outstanding-fines+json:
        example: !include json/sjp.command.add-request-for-outstanding-fines.json
        schema: !include json/schema/sjp.command.add-request-for-outstanding-fines.json

      application/vnd.sjp.command.request-delete-docs+json:
        example: !include json/sjp.command.request-delete-docs.json
        schema: !include json/schema/sjp.command.request-delete-docs.json
