#%RAML 0.8
title: API Using media type in the URL
baseUri: message://command/handler/message/sjp
version: v1

/sjp.handler.command:
  post:
    body:
      application/vnd.sjp.command.update-financial-means+json:
          schema: !include json/schema/sjp.command.update-financial-means.json
          example: !include json/sjp.command.update-financial-means.json

      application/vnd.sjp.command.delete-defendant-financial-means-information+json:
          schema: !include json/schema/sjp.command.delete-defendant-financial-means-information.json
          example: !include json/sjp.command.delete-defendant-financial-means-information.json

      application/vnd.sjp.command.update-employer+json:
          schema: !include json/schema/sjp.command.update-employer.json
          example: !include json/sjp.command.update-employer.json

      application/vnd.sjp.command.delete-employer+json:
          schema: !include json/schema/sjp.command.delete-employer.json
          example: !include json/sjp.command.delete-employer.json

      application/vnd.sjp.command.add-case-document+json:
          schema: !include json/schema/sjp.command.add-case-document.json
          example: !include json/sjp.command.add-case-document.json

      application/vnd.sjp.command.upload-case-document+json:
          schema: !include json/schema/sjp.command.upload-case-document.json
          example: !include json/sjp.command.upload-case-document.json

      application/vnd.sjp.command.create-sjp-case+json:
          schema: !include json/schema/sjp.command.create-sjp-case.json
          example: !include json/sjp.command.create-sjp-case.json

      application/vnd.sjp.command.update-plea+json:
          schema: !include json/schema/sjp.command.update-plea.json
          example: !include json/sjp.command.update-plea.json

      application/vnd.sjp.command.cancel-plea+json:
          schema: !include json/schema/sjp.command.cancel-plea.json
          example: !include json/sjp.command.cancel-plea.json

      application/vnd.sjp.command.plead-online+json:
          schema: !include json/schema/sjp.command.plead-online.json
          example: !include json/sjp.command.plead-online.json

      application/vnd.sjp.command.complete-case+json:
        schema: !include json/schema/sjp.command.complete-case.json
        example: !include json/sjp.command.complete-case.json

      application/vnd.sjp.command.request-withdrawal-all-offences+json:
        schema: !include json/schema/sjp.command.request-withdrawal-all-offences.json
        example: !include json/sjp.command.request-withdrawal-all-offences.json

      application/vnd.sjp.command.cancel-request-withdrawal-all-offences+json:
        schema: !include json/schema/sjp.command.cancel-request-withdrawal-all-offences.json
        example: !include json/sjp.command.cancel-request-withdrawal-all-offences.json

      application/vnd.sjp.command.mark-case-reopened-in-libra+json:
        schema: !include json/schema/sjp.command.mark-case-reopened-in-libra.json
        example: !include json/sjp.command.case-reopened-in-libra.json

      application/vnd.sjp.command.update-case-reopened-in-libra+json:
        schema: !include json/schema/sjp.command.update-case-reopened-in-libra.json
        example: !include json/sjp.command.case-reopened-in-libra.json

      application/vnd.sjp.command.undo-case-reopened-in-libra+json:
        schema: !include json/schema/sjp.command.undo-case-reopened-in-libra.json
        example: !include json/sjp.command.undo-case-reopened-in-libra.json

      application/vnd.sjp.command.update-defendant-details+json:
        schema: !include json/schema/sjp.command.update-defendant-details.json
        example: !include json/sjp.command.update-defendant-details.json

      application/vnd.sjp.command.update-hearing-requirements+json:
        schema: !include json/schema/sjp.command.update-hearing-requirements.json
        example: !include json/sjp.command.update-hearing-requirements.json

      application/vnd.sjp.command.update-defendant-national-insurance-number+json:
        schema: !include json/schema/sjp.command.update-defendant-national-insurance-number.json
        example: !include json/sjp.command.update-defendant-national-insurance-number.json

      application/vnd.sjp.command.start-session+json:
        schema: !include json/schema/sjp.command.start-session.json
        example: !include json/sjp.command.start-session.json

      application/vnd.sjp.command.end-session+json:
        schema: !include json/schema/sjp.command.end-session.json
        example: !include json/sjp.command.end-session.json

      application/vnd.sjp.command.assign-case+json:
        schema: !include json/schema/sjp.command.assign-case.json
        example: !include json/sjp.command.assign-case.json

      application/vnd.sjp.command.unassign-case+json:
        schema: !include json/schema/sjp.command.unassign-case.json
        example: !include json/sjp.command.unassign-case.json

      application/vnd.sjp.command.assign-case-from-candidates-list+json:
        schema: !include json/schema/sjp.command.assign-case-from-candidates-list.json
        example: !include json/sjp.command.assign-case-from-candidates-list.json

      application/vnd.sjp.command.mark-case-ready-for-decision+json:
        schema: !include json/schema/sjp.command.mark-case-ready-for-decision.json
        example: !include json/sjp.command.mark-case-ready-for-decision.json

      application/vnd.sjp.command.unmark-case-ready-for-decision+json:
        schema: !include json/schema/sjp.command.unmark-case-ready-for-decision.json
        example: !include json/sjp.command.unmark-case-ready-for-decision.json

      application/vnd.sjp.command.add-dates-to-avoid+json:
        schema: !include json/schema/sjp.command.add-dates-to-avoid.json
        example: !include json/sjp.command.add-dates-to-avoid.json

      application/vnd.sjp.command.acknowledge-defendant-details-updates+json:
        schema: !include json/schema/sjp.command.acknowledge-defendant-details-updates.json
        example: !include json/sjp.command.acknowledge-defendant-details-updates.json

      application/vnd.sjp.command.refer-case-for-court-hearing+json:
        schema: !include json/schema/sjp.command.refer-case-for-court-hearing.json
        example: !include json/sjp.command.refer-case-for-court-hearing.json

      application/vnd.sjp.command.update-case-listed-in-criminal-courts+json:
        schema: !include json/schema/sjp.command.update-case-listed-in-criminal-courts.json
        example: !include json/sjp.command.update-case-listed-in-criminal-courts.json

      application/vnd.sjp.command.record-case-referral-for-court-hearing-rejection+json:
        schema: !include json/schema/sjp.command.record-case-referral-for-court-hearing-rejection.json
        example: !include json/sjp.command.record-case-referral-for-court-hearing-rejection.json

      application/vnd.sjp.command.record-case-adjourned-to-later-sjp-hearing+json:
        example: !include json/sjp.command.record-case-adjourned-to-later-sjp-hearing.json
        schema:  !include json/schema/sjp.command.record-case-adjourned-to-later-sjp-hearing.json

      application/vnd.sjp.command.record-case-adjournment-to-later-sjp-hearing-elapsed+json:
        example: !include json/sjp.command.record-case-adjournment-to-later-sjp-hearing-elapsed.json
        schema:  !include json/schema/sjp.command.record-case-adjournment-to-later-sjp-hearing-elapsed.json

      application/vnd.sjp.command.store-transparency-report-data+json:
          schema: !include json/schema/sjp.command.store-transparency-report-data.json
          example: !include json/sjp.command.store-transparency-report-data.json

      application/vnd.sjp.command.request-transparency-report+json: !!null

      application/vnd.sjp.command.add-case-note+json:
        example: !include json/sjp.command.add-case-note.json
        schema:  !include json/schema/sjp.command.add-case-note.json
